if [[ -z "$SKIP_SOURCE_PROFILE" ]]; then
    # https://superuser.com/a/313637
    source $HOME/.profile
fi

# Skip re-sourcing of .profile when .bash_profile is edited to prevent PATH from being extended with
# duplicate paths
alias bp='vi $HOME/.bash_profile && SKIP_SOURCE_PROFILE=1 source $HOME/.bash_profile || SKIP_SOURCE_PROFILE=1 source $HOME/.bash_profile'

# https://askubuntu.com/a/22043
alias sudo='sudo '

alias grep='grep -s --color=auto'

alias vi=nvim
alias vim=nvim

alias gitc='vi ~/.gitconfig'
alias sshc='vi ~/.ssh/config'

alias ss='cd ~/Src'
alias ftree='tree -lahgupC'
alias tia='tig --all'

function utime() {
    if [[ -n "$1" ]]; then
        # Translate unix timestamp into human-readable date
        date -r $1
    else
        # Print current date in unix time
        date +%s
    fi
}

function gen-random() {
    cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w "$1" | head -1
}

# Enable forward search through bash history via Ctrl-S
# https://stackoverflow.com/a/791800
stty -ixon

# Default AWS region for all profiles
export AWS_DEFAULT_REGION=us-west-2

for f in $HOME/.bash_profile.d/*; do
   source $f
done

# Bash-specific configuration
if [[ "$SHELL" =~ .*bash$ ]]; then
    # Unlimited bash history
    # https://stackoverflow.com/a/12234989
    export HISTFILESIZE=
    export HISTSIZE=
    # https://superuser.com/a/753158
    export HISTFILE=~/.bash_eternal_history

    # Collapse duplicate commands and update history file incrementally
    setopt HIST_FIND_NO_DUPS
    setopt INC_APPEND_HISTORY

    export LSCOLORS='ExgxfxDxcxDxDxxbaDExEx'
    alias ls='ls -G'

    GIT_PS1_SHOWDIRTYSTATE=true
    GIT_PS1_SHOWCOLORHINTS=true
    GIT_PS1_SHOWUNTRACKEDFILES=true
    GIT_PS1_SHOWUPSTREAM="auto"
    PS1='`if [ -n "$(jobs -p)" ]; then echo "[\j]"; fi`\w$(__git_ps1 " (%s)")$ '

    # Enable bash completion
    [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
fi
